import re
import json
from lc_agent import AIMessage, NetworkModifier, RunnableNetwork, RunnableNode
from .scene_construction_node import SceneConstructionNode
from .tool.generate_terrain_tool import GenerateTerrainTool
from .tool.generate_forest_tool import GenerateForestTool


class SceneConstructionModifier(NetworkModifier):
    """
    Modifier for the RAPID-RTX Scene Construction Expert.

    Responsibilities:

    1. Detect scene construction commands generated by the LLM.
    2. Parse command parameters.
    3. Validate parameters.
    4. Call the corresponding RAPID-RTX Tool.
    5. Return the tool result to the network.

    Supported commands:
        @GenerateTerrain(...)@
        @GenerateForest(...)@
    """
    # GenerateTerrain
    TERRAIN_PATTERN = (
        r'@GenerateTerrain\('
        r'\s*"([^"]+)"\s*,'
        r'\s*([\d.]+)\s*,'
        r'\s*([\d.]+)\s*,'
        r'\s*(\d+)\s*,'
        r'\s*([\d.]+)\s*,'
        r'\s*([\d.]+)'
        r'\s*\)@')

    # GenerateForest
    FOREST_PATTERN = (
        r'@GenerateForest\('
        r'\s*(\d+)\s*,'
        r'\s*([\d.]+)\s*,'
        r'\s*"([^"]+)"\s*,'
        r'\s*([\d.]+)'
        r'\s*\)@')

    async def on_post_invoke_async(self, network: "RunnableNetwork", node: RunnableNode):

        # 1. Get LLM output
        output = node.outputs.content if node.outputs else ""

        if not output:
            print(
                "[RAPID DEBUG] SceneConstructionModifier:"
                " No output.")
            return

        # 2. Detect commands
        terrain_matches = re.findall(self.TERRAIN_PATTERN, output)
        forest_matches = re.findall(self.FOREST_PATTERN, output)
        if not terrain_matches and not forest_matches:
            print("[Chat RAPID] :No Scene Construction command found.")
            return

        # 3. Execute commands
        results = []
        # GenerateTerrain
        terrain_context = None
        for (terrain_type, size_x, size_y, resolution, roughness, slope) in terrain_matches:
            # str字符转成对应数据类型
            size_x = float(size_x)
            size_y = float(size_y)
            resolution = int(resolution)
            roughness = float(roughness)
            slope = float(slope)

            # Validate parameters
            validation_error = self._validate_terrain(
                terrain_type,
                size_x,
                size_y,
                resolution,
                roughness,
                slope)

            if validation_error:
                results.append({
                    "command": "GenerateTerrain",
                    "status": "ERROR",
                    "message": validation_error})
                continue

            # Call Tool
            terrain_result = GenerateTerrainTool.run(
                terrain_type=terrain_type,
                size_x=size_x,
                size_y=size_y,
                resolution=resolution,
                roughness=roughness,
                slope=slope)
            terrain_context = terrain_result["terrain"]
            results.append(terrain_result)

        # GenerateForest
        for (tree_count, lai, species_ratio, average_height) in forest_matches:
            # str字符转成对应数据类型
            tree_count = int(tree_count)
            lai = float(lai)
            average_height = float(average_height)

            # Validate parameters
            validation_error = self._validate_forest(tree_count, lai, species_ratio,
                                                     average_height)

            if validation_error:
                results.append({
                    "command": "GenerateForest",
                    "status": "ERROR",
                    "message": validation_error})
                continue

            # Call Tool
            forest_tool = GenerateForestTool()
            forest_result = await forest_tool.run(
                tree_count=tree_count,
                lai=lai,
                species_ratio=species_ratio,
                average_height=average_height,
                terrain_context=terrain_context,)
            results.append(forest_result)

        # GenerateMaterial

        # 5. Build final result
        results_str = json.dumps(results, indent=2, ensure_ascii=False)

        # 6. Return result to network
        result_node = SceneConstructionNode()
        result_node.outputs = AIMessage(content=results_str)
        network.outputs = result_node.outputs
        network._event_callback(
            RunnableNetwork.Event.NODE_INVOKED,
            {
                "node": network,
                "network": network})
        node >> result_node

    @staticmethod
    def _validate_terrain(terrain_type, size_x, size_y, resolution, roughness, slope):
        '''Terrain validation'''
        valid_types = {"flat", "hilly", "mountain", "valley"}

        if terrain_type not in valid_types:
            return (f"Invalid terrain_type: {terrain_type}. "
                    f"Supported values: {valid_types}")
        if size_x <= 0:
            return "size_x must be greater than 0."
        if size_y <= 0:
            return "size_y must be greater than 0."
        if resolution <= 1:
            return "resolution must be greater than 1."
        if roughness < 0:
            return "roughness must be greater than or equal to 0."
        if not 0 <= slope <= 90:
            return "slope must be between 0 and 90 degrees."

        return None

    @staticmethod
    def _validate_forest(tree_count, lai, species_ratio, average_height):
        '''Forest validation'''
        if tree_count <= 0:
            return "tree_count must be greater than 0."
        if lai <= 0:
            return "lai must be greater than 0."
        if average_height <= 0:
            return "average_height must be greater than 0."

        # Parse species ratio ，对这个参数的验证可以再仔细一点，后便可以把这个封装到一个py中。
        try:
            species_items = (species_ratio.split(","))
            total_ratio = 0.0
            for item in species_items:
                species, ratio = (item.split(":"))
                ratio = float(ratio)
                if ratio < 0 or ratio > 1:
                    return (f"Invalid species ratio: "f"{ratio}")
                total_ratio += ratio

            if abs(total_ratio - 1.0) > 1e-6:
                return ("Species ratios must sum to 1.0. "f"Current sum: {total_ratio}")

        except Exception:
            return ("Invalid species_ratio format. "'Expected: "pine:0.7,oak:0.3"')
        return None
